steps:

# Build image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '--build-arg'
    - 'REACT_APP_API_URL=https://anikait-backend-79505229087.northamerica-northeast2.run.app/api/v1'
    - '-t'
    - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/anikait-repo/frontend:$COMMIT_SHA'
    - './frontend'

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/anikait-repo/frontend:$COMMIT_SHA'

# Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - anikait-frontend
    - '--image'
    - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/anikait-repo/frontend:$COMMIT_SHA'
    - '--region'
    - 'northamerica-northeast2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/anikait-repo/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY